name: CI/CD para pagina web en Azure

on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio de forma local
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Descargar dependencias
        run: dotnet restore UsersWeb.sln

      - name: Compilar en modo Release
        run: dotnet build UsersWeb.sln --configuration Release --no-restore

      - name: Ejecutar pruebas
        run: dotnet test UsersWeb.Tests/UsersWeb.Tests.csproj --configuration Release --no-build --verbosity minimal

      - name: Publicar
        run: dotnet publish UsersWeb/UsersWeb.csproj -c Release -o published

      - name: Exportar ensamblado para publicar (artefacto)
        uses: actions/upload-artifact@v4
        with:
          name: usersweb-published
          path: published/

  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Descargar ensamblado (artefacto)
        uses: actions/download-artifact@v4
        with:
          name: usersweb-published

      - name: Iniciar sesion en Azure
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Despliegue de app web en Azure
        id: desplegar-en-azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: "random-users-web"
          slot-name: "Production"
          package: .
